### ISSUE TITLE
Clip path not working in safari?

### ISSUE THREAD

**Issue by superandrew** [Apress/architecting-css#2]
I tried with the css in chapter one to display 3 stars:

```

.shape {
-webkit-clip-path: polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%);
  display: inline-block;
  position: relative;
  height: calc(100vw / 3);
  width: calc(100vw / 3);
  border: 1px solid blue;
}
.shape:nth-of-type(1) {
  background: rgba(255, 0, 255, 0.31);
  transform: rotate(-25deg);
  filter: saturate(15%);
}
.shape:nth-of-type(2) {
  background: rgb(255,116,0);
  background: linear-gradient(90deg, rgba(255,116,0,1) 0%, rgba(255,237,0,1) 47%, rgba(255,167,0,1) 100%);
  filter: opacity(.75);
  transform: translate(0, -50px);
  left: calc((100vw / 3) - 200px);
}
.shape:nth-of-type(3) {
  background: hsl(189, 100%, 50%);
  transform: rotate(25deg);
  opacity: .33;
  left: calc((100vw / 3) - 100px);
  top: -200px;
}
```
html
```
<body>
  <h1> Functions</h1>
<div class="shape"></div>
<div class="shape"></div>
<div class="shape"></div>
</body>
```
I see no stars. Is there a support problem for some browsers? I am on a mac with safari and chrome.

**Comment by martine-dowden** [comment]
Hi @superandrew, It looks like you have a prefix in front of the clip-path `-webkit-clip-path`, try removing it or adding the un-prefixed version after `clip-path: polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%);` and should work.
[Can I use](https://caniuse.com/?search=clip-path) says that in safari, it is supported unless you are working with an external svg file, which is not the case here 

What is interesting is that copy pasting your code above into [codepen](https://codepen.io/martine-dowden/pen/yLaGQgj) with no edits works in my version of safari so could be a safari version issue: I am running 14.0
![Screen Shot 2021-01-16 at 2 45 19 PM](https://user-images.githubusercontent.com/17507258/104821355-22feb580-5809-11eb-84e2-0915c918d1f2.png)

Also noticed the index files got uploaded as word docs instead of html files, sorry about that will work on getting that fixed here shortly.

**Comment by superandrew** [comment]
Hi @martine-dowden thank you. Yes, I added the -webkit prefix just to be sure, but that was a try. Anyway the problem was caused by copying and pasting the code, some character was in the way so the properties weren't read correctly. Everything works now, thank you, I'm loving the book so far!
